##########################################################################
# ph0llux:821d53e89cda4a5a6d37548073153558cb100dbb4bfc790510799768fe2385a1
##########################################################################
unstable_features = true
max_width = 120
reorder_imports = true
fn_args_layout = "Tall"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
wrap_comments = true
comment_width = 120
edition = "2018"
format_code_in_doc_comments = true
format_strings = true
imports_layout = "Horizontal"
hard_tabs = true
tab_spaces = 4