##########################################################################
# ph0llux:e4c9d58ffb180a48e086c40a1663d5e1d020962b9f0ab7aed20cb9804ec9deaf
##########################################################################
#########################################################################
# pk:c7748221387b7336ac5c4d817acaccc2892578a3ce179eb61fa6935cd02a6725
#########################################################################
unstable_features = true
max_width = 120
reorder_imports = true
fn_args_layout = "Tall"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
wrap_comments = true
comment_width = 120
edition = "2018"
format_code_in_doc_comments = true
format_strings = true
imports_layout = "Horizontal"
hard_tabs = true
tab_spaces = 4